project:
  type: website

website:
  title: Messing with LLMs heads!!!"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mdbodonnell

format:
  html:
    theme: sketchy
    css: styles.css

execute:
  freeze: auto


